
#数据库配置
spring:
  datasource:
      url: jdbc:mysql://192.168.207.128:3306/newsappdb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /**
    date-format: yyyy-MM-dd






#端口配置
server:
  port: 80


#扫描实体类和Mapper.xml
mybatis:
  type-aliases-package: com.zxtt.newsapp.commons.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full



logging:
  level:
    com.zxtt.newsapp.commons.mapper : debug  #dao的路径
